### ISSUE TITLE
Is the large dataset available?

### ISSUE THREAD

**Issue by JunMa11** [UBC-CIC/COVID19-L3-Net#1]
Thanks for sharing the great work.

Is the large dataset available?

![image](https://user-images.githubusercontent.com/19947331/81907077-cdc73000-95f9-11ea-93e2-3dd4f28b42f7.png)

**Comment by shensmobile** [comment]
Unfortunately we are not able to share the dataset due to privacy limitations.  The best we can do in the meanwhile is to provide our training algorithms and weights so that you can vet our approach and take the weights and reinforce with your own local data.

**Comment by JunMa11** [comment]
Got it. Thanks for your great efforts very much.
