### ISSUE TITLE
Can't download phase 2 model's weight

### ISSUE THREAD

**Issue by hrdipto** [UBC-CIC/COVID19-L3-Net#3]
UNet2D Weights (Phase 2 Soft Labels) : https://s3.ca-central-1.amazonaws.com/ubccic.covid19.models/phase2_model.ckpt is not working.
Error: AccessDenied

**Comment by klensink** [comment]
Thank you for letting us know. I've updated the permissions, could you try again?

**Comment by hrdipto** [comment]
Yes it's working now @klensink

**Comment by LiMufeng123** [comment]
Now it's not possible to download the weight file again. Can you update the permissions
